In [3]:
import pandas as pd
import os

In [4]:
data_path = "../data/raw"
files = os.listdir(data_path)

for file in files:
    print(file)

01_خدمات_فناوری_خرداد_1405.xlsx
02_پشتیبانی_خرداد_1405.xlsx
03_تعداد_نفرات_خرداد_1405.xlsx
04_خدمات_فناوری_تیر_1405.xlsx
05_پشتیبانی_تیر_1405.xlsx
06_تعداد_نفرات_تیر_1405.xlsx

In [5]:
from pathlib import Path

data_path = Path("../data/raw")
files = list(data_path.glob("*.xlsx"))
for file in files:
    print(file.name)

01_خدمات_فناوری_خرداد_1405.xlsx
02_پشتیبانی_خرداد_1405.xlsx
03_تعداد_نفرات_خرداد_1405.xlsx
04_خدمات_فناوری_تیر_1405.xlsx
05_پشتیبانی_تیر_1405.xlsx
06_تعداد_نفرات_تیر_1405.xlsx

In [6]:
import sys

print(sys.executable)

In [13]:
file_summery = []

for file in files:
    df = pd.read_excel(file)

    file_summery.append({
        "file_name": file.name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "colmun_names": list(df.columns)
    })

summery_df = pd.DataFrame(file_summery)
summery_df

,file_name,rows,columns,colmun_names
0,01_خدمات_فناوری_خرداد_1405.xlsx,8,7,"[ردیف, نام شرکت, شرح خدمت, مبلغ, ماه, روش تخصی..."
1,02_پشتیبانی_خرداد_1405.xlsx,7,6,"[Company, Cost Title, Amount (Rial), Period, A..."
2,03_تعداد_نفرات_خرداد_1405.xlsx,5,4,"[کد شرکت, شرکت, تعداد نفرات, دوره]"
3,04_خدمات_فناوری_تیر_1405.xlsx,10,8,"[شماره, شرکت, نوع خدمت, مبلغ (ریال), دوره, نحو..."
4,05_پشتیبانی_تیر_1405.xlsx,9,7,"[نام شرکت, عنوان هزینه, مبلغ, ماه, مبنای تسهیم..."
5,06_تعداد_نفرات_تیر_1405.xlsx,5,5,"[Company ID, Company Name, Headcount, Month, U..."

In [17]:
file_name = files[0]
df = pd.read_excel(file_name)
df.describe()

          ردیف          مبلغ
count  8.00000  8.000000e+00
mean   4.50000  2.137500e+08
std    2.44949  1.245515e+08
min    1.00000  6.800000e+07
25%    2.75000  1.367500e+08
50%    4.50000  1.845000e+08
75%    6.25000  2.750000e+08
max    8.00000  4.200000e+08

In [20]:
df.head()

   ردیف      نام شرکت          شرح خدمت       مبلغ      ماه روش تخصیص توضیحات
0     1     شرکت آلفا  لایسنس نرم‌افزار  245000000  1405/03    مستقیم     NaN
1     2      شرکت بتا  لایسنس نرم‌افزار  198000000  1405/03    مستقیم     NaN
2     3     شرکت گاما      زیرساخت ابری  365000000  1405/03    مستقیم     NaN
3     4          دلتا   پشتیبانی سامانه  152000000  1405/03    مستقیم     NaN
4     5  شرکت اپسیلون     لایسنس امنیتی  171000000  1405/03    مستقیم     NaN

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes

In [18]:
df.isnull().sum()

ردیف         0
نام شرکت     0
شرح خدمت     0
مبلغ         0
ماه          0
روش تخصیص    0
توضیحات      7
dtype: int64

In [23]:
df.columns

Index(['ردیف', 'نام شرکت', 'شرح خدمت', 'مبلغ', 'ماه', 'روش تخصیص', 'توضیحات'], dtype='str')

In [26]:
df["مبلغ"].value_counts()

مبلغ
245000000    1
198000000    1
365000000    1
152000000    1
171000000    1
420000000    1
68000000     1
91000000     1
Name: count, dtype: int64

In [27]:
df["مبلغ"].unique()

array([245000000, 198000000, 365000000, 152000000, 171000000, 420000000,
        68000000,  91000000])

بررسی نوع داده های هر ستون

In [ ]:
for file in files: 
    print(f"file name: {file.name}")
    df.info()
    print("___________")

file name: 01_خدمات_فناوری_خرداد_1405.xlsx
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes
___________
file name: 02_پشتیبانی_خرداد_1405.xlsx
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes
___________
file name: 03_تعداد_نفرات_خرداد_1405.xlsx
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes
___________
file name: 04_خدمات_فناوری_تیر_1405.xlsx
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes
___________
file name: 05_پشتیبانی_تیر_1405.xlsx
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes
___________
file name: 06_تعداد_نفرات_تیر_1405.xlsx
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ردیف       8 non-null      int64
 1   نام شرکت   8 non-null      str
 2   شرح خدمت   8 non-null      str
 3   مبلغ       8 non-null      int64
 4   ماه        8 non-null      str
 5   روش تخصیص  8 non-null      str
 6   توضیحات    1 non-null      str
dtypes: int64(2), str(5)
memory usage: 580.0 bytes
___________

بررسی محتوای ستون ها 
برای اینکه بتونیم ببینیم چه شکل هایی از مثلا اسم شرکت در ستون شرکت داریم

In [42]:
for file in files:
    df = pd.read_excel(file)
    print(f"file name: {file.name}")
    columns = df.columns
    print("columns:")
    for column in columns: 
        print(f"\nColumn: {column}")
        print(df[column].unique())
    print("________")

file name: 01_خدمات_فناوری_خرداد_1405.xlsx
columns:

Column: ردیف
[1 2 3 4 5 6 7 8]

Column: نام شرکت
<StringArray>
[   'شرکت آلفا',     'شرکت بتا',    'شرکت گاما',         'دلتا',
 'شرکت اپسیلون',  'همه شرکت‌ها',         'آلفا']
Length: 7, dtype: str

Column: شرح خدمت
<StringArray>
[   'لایسنس نرم‌افزار',        'زیرساخت ابری',     'پشتیبانی سامانه',
       'لایسنس امنیتی', 'اشتراک ابزار همکاری',     'فضای ذخیره‌سازی',
    'خدمات مانیتورینگ']
Length: 7, dtype: str

Column: مبلغ
[245000000 198000000 365000000 152000000 171000000 420000000  68000000
  91000000]

Column: ماه
<StringArray>
['1405/03']
Length: 1, dtype: str

Column: روش تخصیص
<StringArray>
['مستقیم', 'مساوی']
Length: 2, dtype: str

Column: توضیحات
<StringArray>
[nan, 'هزینه مشترک ماهانه']
Length: 2, dtype: str
________
file name: 02_پشتیبانی_خرداد_1405.xlsx
columns:

Column: Company
<StringArray>
['Alpha', 'شرکت بتا', 'Gamma Co', 'شرکت دلتا', 'Epsilon', 'ALL']
Length: 6, dtype: str

Column: Cost Title
<StringArray>
['Office Supplies',         'Courier', 'Facility Repair',   'Shared Office',
 'General Support']
Length: 5, dtype: str

Column: Amount (Rial)
[ 74000000  51000000  86000000  63000000  47000000 610000000 250000000]

Column: Period
<StringArray>
['1405-03']
Length: 1, dtype: str

Column: Allocation Basis
<StringArray>
['Direct', 'Headcount', 'Equal']
Length: 3, dtype: str

Column: Reference
<StringArray>
['SUP-0301', 'SUP-0302', 'SUP-0303', 'SUP-0304', 'SUP-0305', 'SUP-0306',
 'SUP-0307']
Length: 7, dtype: str
________
file name: 03_تعداد_نفرات_خرداد_1405.xlsx
columns:

Column: کد شرکت
[101 102 103 104 105]

Column: شرکت
<StringArray>
['شرکت آلفا', 'شرکت بتا', 'شرکت گاما', 'شرکت دلتا', 'شرکت اپسیلون']
Length: 5, dtype: str

Column: تعداد نفرات
[128  84  96  71  59]

Column: دوره
<StringArray>
['1405/03']
Length: 1, dtype: str
________
file name: 04_خدمات_فناوری_تیر_1405.xlsx
columns:

Column: شماره
[ 1  2  3  4  5  6  7  8  9 10]

Column: شرکت
<StringArray>
[     'آلفا',   'Beta Co', 'شرکت گاما', 'شرکت دلتا',   'اپسیلون',       'همه',
 'شرکت آلفا',  'شرکت بتا']
Length: 8, dtype: str

Column: نوع خدمت
<StringArray>
[   'لایسنس نرم‌افزار',        'زیرساخت ابری',     'پشتیبانی سامانه',
       'لایسنس امنیتی', 'اشتراک ابزار همکاری',     'فضای ذخیره‌سازی',
    'خدمات مانیتورینگ',    'خدمات تحلیل داده']
Length: 8, dtype: str

Column: مبلغ (ریال)
[2.52e+08 2.04e+08 3.72e+08 1.49e+08      nan 4.50e+08 7.20e+07 9.40e+07
 7.80e+08]

Column: دوره
<StringArray>
['1405/04']
Length: 1, dtype: str

Column: نحوه تخصیص
<StringArray>
['مستقیم', 'مساوی']
Length: 2, dtype: str

Column: مرکز هزینه
<StringArray>
['IT-01', 'IT-02', 'IT-03', 'IT-04', 'IT-05', 'IT-06']
Length: 6, dtype: str

Column: شرح
<StringArray>
[nan, 'عدد در فایل ارسالی ثبت نشده', 'پروژه ویژه']
Length: 3, dtype: str
________
file name: 05_پشتیبانی_تیر_1405.xlsx
columns:

Column: نام شرکت
<StringArray>
[   'شرکت آلفا',          'بتا',    'شرکت گاما',     'Delta Co',
 'شرکت اپسیلون',  'همه شرکت‌ها',          'ALL',    'شرکت امگا',
     'شرکت بتا']
Length: 9, dtype: str

Column: عنوان هزینه
<StringArray>
[     'لوازم اداری',      'پیک و ارسال',          'تعمیرات',
 'فضای اداری مشترک',   'پشتیبانی عمومی',        'خدمات چاپ',
    'خدمات پذیرایی']
Length: 7, dtype: str

Column: مبلغ
[ 79000000  55000000 -12000000  67000000  49000000 645000000 270000000
  33000000  42000000]

Column: ماه
<StringArray>
['1405/04', '1405/03']
Length: 2, dtype: str

Column: مبنای تسهیم
<StringArray>
['مستقیم', 'تعداد نفرات', 'مساوی']
Length: 3, dtype: str

Column: کد پیگیری
<StringArray>
['SUP-0401', 'SUP-0402', 'SUP-0403', 'SUP-0404', 'SUP-0405', 'SUP-0406',
 'SUP-0407', 'SUP-0408', 'SUP-0409']
Length: 9, dtype: str

Column: وضعیت
<StringArray>
['ثبت‌شده', 'اصلاحیه']
Length: 2, dtype: str
________
file name: 06_تعداد_نفرات_تیر_1405.xlsx
columns:

Column: Company ID
[101 102 103 104 105]

Column: Company Name
<StringArray>
['Alpha Co', 'شرکت بتا', 'گاما', 'شرکت دلتا', 'Epsilon']
Length: 5, dtype: str

Column: Headcount
[131.  87. 101.  72.  nan]

Column: Month
<StringArray>
['1405/04']
Length: 1, dtype: str

Column: Updated At
<StringArray>
['1405/05/02']
Length: 1, dtype: str
________

بررسی مقادیر خالی در ستون ها

In [48]:
for file in files:
    df = pd.read_excel(file)
    print(f"\nfile name: {file.name}")
    columns = df.columns
    print(f"\ncolumns:")
    for column in columns: 
        print(f"Column: {column}")
        print(df[column].isnull().sum())
    print("________")

file name: 01_خدمات_فناوری_خرداد_1405.xlsx

columns:
Column: ردیف
0
Column: نام شرکت
0
Column: شرح خدمت
0
Column: مبلغ
0
Column: ماه
0
Column: روش تخصیص
0
Column: توضیحات
7
________

file name: 02_پشتیبانی_خرداد_1405.xlsx

columns:
Column: Company
0
Column: Cost Title
0
Column: Amount (Rial)
0
Column: Period
0
Column: Allocation Basis
0
Column: Reference
0
________

file name: 03_تعداد_نفرات_خرداد_1405.xlsx

columns:
Column: کد شرکت
0
Column: شرکت
0
Column: تعداد نفرات
0
Column: دوره
0
________

file name: 04_خدمات_فناوری_تیر_1405.xlsx

columns:
Column: شماره
0
Column: شرکت
0
Column: نوع خدمت
0
Column: مبلغ (ریال)
1
Column: دوره
0
Column: نحوه تخصیص
0
Column: مرکز هزینه
0
Column: شرح
7
________

file name: 05_پشتیبانی_تیر_1405.xlsx

columns:
Column: نام شرکت
0
Column: عنوان هزینه
0
Column: مبلغ
0
Column: ماه
0
Column: مبنای تسهیم
0
Column: کد پیگیری
0
Column: وضعیت
0
________

file name: 06_تعداد_نفرات_تیر_1405.xlsx

columns:
Column: Company ID
0
Column: Company Name
0
Column: Headcount
1
Column: Month
0
Column: Updated At
0
________

بررسی مقادیر غیر عادی 
برای تشخیص مبلغ عجیب یا منفی

In [54]:
for file in files:
    df = pd.read_excel(file)
    print(f"file name: {file.name}")
    columns = df.columns
    print("columns:")
    for column in columns: 
        print(f"\nColumn: {column}")
        print(df[column].describe())
        print(f"\n*****")
    print("________")

file name: 01_خدمات_فناوری_خرداد_1405.xlsx
columns:

Column: ردیف
count    8.00000
mean     4.50000
std      2.44949
min      1.00000
25%      2.75000
50%      4.50000
75%      6.25000
max      8.00000
Name: ردیف, dtype: float64

*****

Column: نام شرکت
count            8
unique           7
top       شرکت بتا
freq             2
Name: نام شرکت, dtype: object

*****

Column: شرح خدمت
count                    8
unique                   7
top       لایسنس نرم‌افزار
freq                     2
Name: شرح خدمت, dtype: object

*****

Column: مبلغ
count    8.000000e+00
mean     2.137500e+08
std      1.245515e+08
min      6.800000e+07
25%      1.367500e+08
50%      1.845000e+08
75%      2.750000e+08
max      4.200000e+08
Name: مبلغ, dtype: float64

*****

Column: ماه
count           8
unique          1
top       1405/03
freq            8
Name: ماه, dtype: object

*****

Column: روش تخصیص
count          8
unique         2
top       مستقیم
freq           7
Name: روش تخصیص, dtype: object

*****

Column: توضیحات
count                      1
unique                     1
top       هزینه مشترک ماهانه
freq                       1
Name: توضیحات, dtype: object

*****
________
file name: 02_پشتیبانی_خرداد_1405.xlsx
columns:

Column: Company
count       7
unique      6
top       ALL
freq        2
Name: Company, dtype: object

*****

Column: Cost Title
count                   7
unique                  5
top       Office Supplies
freq                    2
Name: Cost Title, dtype: object

*****

Column: Amount (Rial)
count    7.000000e+00
mean     1.687143e+08
std      2.069619e+08
min      4.700000e+07
25%      5.700000e+07
50%      7.400000e+07
75%      1.680000e+08
max      6.100000e+08
Name: Amount (Rial), dtype: float64

*****

Column: Period
count           7
unique          1
top       1405-03
freq            7
Name: Period, dtype: object

*****

Column: Allocation Basis
count          7
unique         3
top       Direct
freq           5
Name: Allocation Basis, dtype: object

*****

Column: Reference
count            7
unique           7
top       SUP-0301
freq             1
Name: Reference, dtype: object

*****
________
file name: 03_تعداد_نفرات_خرداد_1405.xlsx
columns:

Column: کد شرکت
count      5.000000
mean     103.000000
std        1.581139
min      101.000000
25%      102.000000
50%      103.000000
75%      104.000000
max      105.000000
Name: کد شرکت, dtype: float64

*****

Column: شرکت
count             5
unique            5
top       شرکت آلفا
freq              1
Name: شرکت, dtype: object

*****

Column: تعداد نفرات
count      5.000000
mean      87.600000
std       26.500943
min       59.000000
25%       71.000000
50%       84.000000
75%       96.000000
max      128.000000
Name: تعداد نفرات, dtype: float64

*****

Column: دوره
count           5
unique          1
top       1405/03
freq            5
Name: دوره, dtype: object

*****
________
file name: 04_خدمات_فناوری_تیر_1405.xlsx
columns:

Column: شماره
count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
Name: شماره, dtype: float64

*****

Column: شرکت
count            10
unique            8
top       شرکت گاما
freq              3
Name: شرکت, dtype: object

*****

Column: نوع خدمت
count                   10
unique                   8
top       لایسنس نرم‌افزار
freq                     2
Name: نوع خدمت, dtype: object

*****

Column: مبلغ (ریال)
count    9.000000e+00
mean     3.503333e+08
std      2.725858e+08
min      7.200000e+07
25%      1.490000e+08
50%      2.520000e+08
75%      4.500000e+08
max      7.800000e+08
Name: مبلغ (ریال), dtype: float64

*****

Column: دوره
count          10
unique          1
top       1405/04
freq           10
Name: دوره, dtype: object

*****

Column: نحوه تخصیص
count         10
unique         2
top       مستقیم
freq           9
Name: نحوه تخصیص, dtype: object

*****

Column: مرکز هزینه
count        10
unique        6
top       IT-01
freq          2
Name: مرکز هزینه, dtype: object

*****

Column: شرح
count              3
unique             2
top       پروژه ویژه
freq               2
Name: شرح, dtype: object

*****
________
file name: 05_پشتیبانی_تیر_1405.xlsx
columns:

Column: نام شرکت
count             9
unique            9
top       شرکت آلفا
freq              1
Name: نام شرکت, dtype: object

*****

Column: عنوان هزینه
count               9
unique              7
top       لوازم اداری
freq                2
Name: عنوان هزینه, dtype: object

*****

Column: مبلغ
count    9.000000e+00
mean     1.364444e+08
std      2.063141e+08
min     -1.200000e+07
25%      4.200000e+07
50%      5.500000e+07
75%      7.900000e+07
max      6.450000e+08
Name: مبلغ, dtype: float64

*****

Column: ماه
count           9
unique          2
top       1405/04
freq            8
Name: ماه, dtype: object

*****

Column: مبنای تسهیم
count          9
unique         3
top       مستقیم
freq           7
Name: مبنای تسهیم, dtype: object

*****

Column: کد پیگیری
count            9
unique           9
top       SUP-0401
freq             1
Name: کد پیگیری, dtype: object

*****

Column: وضعیت
count           9
unique          2
top       ثبت‌شده
freq            8
Name: وضعیت, dtype: object

*****
________
file name: 06_تعداد_نفرات_تیر_1405.xlsx
columns:

Column: Company ID
count      5.000000
mean     103.000000
std        1.581139
min      101.000000
25%      102.000000
50%      103.000000
75%      104.000000
max      105.000000
Name: Company ID, dtype: float64

*****

Column: Company Name
count            5
unique           5
top       Alpha Co
freq             1
Name: Company Name, dtype: object

*****

Column: Headcount
count      4.000000
mean      97.750000
std       25.131322
min       72.000000
25%       83.250000
50%       94.000000
75%      108.500000
max      131.000000
Name: Headcount, dtype: float64

*****

Column: Month
count           5
unique          1
top       1405/04
freq            5
Name: Month, dtype: object

*****

Column: Updated At
count              5
unique             1
top       1405/05/02
freq               5
Name: Updated At, dtype: object

*****
________